apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api2.name }}
  labels:
    {{- include "uv-monorepo.labels" . | nindent 4 }}
    {{- include "uv-monorepo.selectorLabels" .Values.api2.name | nindent 4 }}
spec:
  replicas: {{ .Values.api2.replicas }}
  selector:
    matchLabels:
      {{- include "uv-monorepo.selectorLabels" .Values.api2.name | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "uv-monorepo.selectorLabels" .Values.api2.name | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.api2.name }}
          image: "{{ .Values.api2.image }}:{{ .Values.api2.tag }}"
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.api2.port }}
          resources:
            {{- toYaml .Values.api2.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /number/random/1
              port: {{ .Values.api2.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /number/random/1
              port: {{ .Values.api2.port }}
            initialDelaySeconds: 3
            periodSeconds: 5
